import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { emptyRecord, defaults } from '../lib/schema.mjs';
import { seed } from '../lib/seed.mjs';
import { createAdmin, login, getSession, logout } from '../lib/auth.mjs';
import { importData } from '../lib/import.mjs';
export const productData = (extra={}) => ({...emptyRecord('products'),title:'Producto de prueba',slug:'producto-prueba',status:'published',image:'https://images.example.com/product.jpg',presentation:'70 servicios',price:55000,availability:'available',...extra});
export const orderData = (product,extra={}) => ({requestId:randomUUID(),customerName:'Comprador de prueba',phone:'3001234567',city:'Bogotá',department:'Cundinamarca',address:'Dirección de prueba',status:'new',paymentMethod:'Nequi',paymentStatus:'pending',paymentAmount:0,shippingCost:9000,items:[{lineId:randomUUID(),kind:'products',itemId:product.id,quantity:1,unitPrice:product.price}],...extra});
export const contracts = [
 ['inicializa una base vacía sin inventar pedidos',async s=>{assert.equal((await s.orders()).length,0);assert.equal((await s.settings()).whatsapp,'573043440035');assert.equal((await s.settings()).launchApproved,false);}],
 ['seed usa datos entregados y es repetible sin duplicarlos',async s=>{assert.equal(await seed(s),true);assert.equal(await seed(s),false);assert.equal((await s.list('products')).length,1);assert.equal((await s.list('catalogs')).length,4);assert.equal((await s.orders()).length,0);assert.equal((await s.list('products'))[0].price,55000);}],
 ['crea edita publica y archiva productos',async s=>{const p=await s.save('products',productData());const changed=await s.save('products',{...p,price:65000},p.id,p.version);assert.equal(changed.price,65000);assert.equal(changed.version,2);await s.save('products',{...changed,status:'archived'},p.id,2);assert.equal((await s.publicData()).products.length,0);}],
 ['evita direcciones cortas repetidas',async s=>{await s.save('products',productData());await assert.rejects(()=>s.save('products',productData()),{status:409});}],
 ['no sobrescribe ediciones concurrentes',async s=>{const p=await s.save('products',productData());const results=await Promise.allSettled([s.save('products',{...p,price:60000},p.id,1),s.save('products',{...p,price:70000},p.id,1)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);}],
 ['guarda URLs y referencias de imagen local sin contenido binario en la base',async s=>{const p=await s.save('products',productData());assert.equal(p.image,'https://images.example.com/product.jpg');const local='/api/media/550e8400-e29b-41d4-a716-446655440000',saved=await s.save('products',productData({slug:'producto-imagen-local',image:local}));assert.equal(saved.image,local);const raw=await s.db.get(`SELECT data FROM ${s.t('records')} WHERE id=?`,[p.id]);assert.ok(!raw.data.includes('bytes'));await assert.rejects(()=>s.save('products',productData({slug:'invalid-upload',image:'/api/media/123'})));}],
 ['validaciones de publicación no impiden guardar borradores',async s=>{await assert.rejects(()=>s.save('products',productData({image:''})));const draft=await s.save('products',{...productData(),status:'draft',image:'',price:0});assert.equal(draft.status,'draft');}],
 ['catálogos se asocian a productos y protegen dependencias',async s=>{const c=await s.save('catalogs',{...emptyRecord('catalogs'),title:'Creatinas',slug:'creatinas',status:'published'});const p=await s.save('products',productData({catalogIds:[c.id]}));await assert.rejects(()=>s.remove('catalogs',c.id,c.version),{status:409});assert.equal(p.catalogIds[0],c.id);}],
 ['relaciones inexistentes no se guardan',async s=>{await assert.rejects(()=>s.save('products',productData({catalogIds:['no-existe']})));assert.equal((await s.list('products')).length,0);}],
 ['combos requieren productos publicados',async s=>{const p=await s.save('products',productData({status:'draft'}));await assert.rejects(()=>s.save('combos',{...emptyRecord('combos'),title:'Combo',slug:'combo',status:'published',price:60000,items:[{productId:p.id,quantity:1}]}));}],
 ['oculta combos con componentes archivados',async s=>{const p=await s.save('products',productData());await s.save('combos',{...emptyRecord('combos'),title:'Combo',slug:'combo',status:'published',price:50000,items:[{productId:p.id,quantity:1}]});await s.save('products',{...p,status:'archived'},p.id,1);assert.equal((await s.publicData()).combos.length,0);}],
 ['indica combo agotado y no permite nuevos pedidos',async s=>{const p=await s.save('products',productData());const c=await s.save('combos',{...emptyRecord('combos'),title:'Combo',slug:'combo',status:'published',price:50000,items:[{productId:p.id,quantity:1}]});await s.save('products',{...p,availability:'soldout'},p.id,1);assert.equal((await s.publicData()).combos[0].availability,'soldout');await assert.rejects(()=>s.saveOrder(orderData(p,{items:[{kind:'combos',itemId:c.id,quantity:1,unitPrice:50000}]}),'operador'));}],
 ['preguntas frecuentes y mensajes solo publicados en web',async s=>{await s.save('faqs',{...emptyRecord('faqs'),title:'Envíos',slug:'envios',answer:'Consultar'});await s.save('messages',{...emptyRecord('messages'),title:'Promoción',slug:'promo',placement:'feature',status:'published',body:'Texto revisado'});assert.equal((await s.publicData()).faqs.length,0);assert.equal((await s.publicData()).messages.length,1);}],
 ['datos de envío editables y públicos solo al publicar',async s=>{await s.save('shipping',{...emptyRecord('shipping'),title:'Envíos de prueba',slug:'envios',status:'published',zone:'Zona confirmada',costText:'Cotizar',estimatedTime:'Confirmar',cashOnDelivery:'Sujeto a cobertura'});assert.equal((await s.publicData()).shipping[0].zone,'Zona confirmada');}],
 ['redes sociales y WhatsApp usan configuración guardada',async s=>{const old=await s.settings();const updated=await s.saveSettings({...old,facebook:'https://www.facebook.com/allnutrition',instagram:'https://www.instagram.com/allnutrition'},old.version);assert.equal(updated.version,2);await assert.rejects(()=>s.saveSettings(old,old.version),{status:409});assert.equal((await s.publicData()).settings.instagram,updated.instagram);}],
 ['los datos públicos no incluyen configuración interna o pedidos',async s=>{const p=await s.save('products',productData());await s.saveOrder(orderData(p),'operador');const data=await s.publicData();assert.equal('orders' in data,false);assert.equal('showNextStage' in data.settings,false);assert.ok(!JSON.stringify(data).includes('Comprador de prueba'));}],
 ['el total se calcula en servidor y no se confía en el navegador',async s=>{const p=await s.save('products',productData());const o=await s.saveOrder(orderData(p,{total:1}),'operador');assert.equal(o.total,64000);assert.equal(o.subtotal,55000);assert.equal(o.number,1);}],
 ['un reintento idéntico devuelve el mismo pedido',async s=>{const p=await s.save('products',productData()),data=orderData(p);const [a,b]=await Promise.all([s.saveOrder(data,'operador'),s.saveOrder(data,'operador')]);assert.equal(a.id,b.id);assert.equal((await s.orders()).length,1);}],
 ['no reutiliza el identificador de guardado con otros datos',async s=>{const p=await s.save('products',productData()),data=orderData(p);await s.saveOrder(data,'operador');await assert.rejects(()=>s.saveOrder({...data,city:'Otra ciudad'},'operador'),{status:409});}],
 ['los números de pedidos concurrentes son únicos',async s=>{const p=await s.save('products',productData());const orders=await Promise.all(Array.from({length:12},()=>s.saveOrder(orderData(p),'operador')));assert.equal(new Set(orders.map(o=>o.number)).size,12);assert.deepEqual(orders.map(o=>o.number).sort((a,b)=>a-b),Array.from({length:12},(_,i)=>i+1));}],
 ['pedidos invalidos revierten contador y registros',async s=>{const p=await s.save('products',productData());await assert.rejects(()=>s.saveOrder(orderData(p,{items:[]}),'operador'));const o=await s.saveOrder(orderData(p),'operador');assert.equal(o.number,1);}],
 ['aplica secuencia de estados e historial',async s=>{const p=await s.save('products',productData());let o=await s.saveOrder(orderData(p),'operador');await assert.rejects(()=>s.saveOrder({...o,status:'delivered',carrier:'Prueba',tracking:'GUIA'},'operador',o.id,o.version),{status:409});o=await s.saveOrder({...o,status:'preparing'},'operador',o.id,o.version);o=await s.saveOrder({...o,status:'sent',carrier:'Transportadora prueba',tracking:'PRUEBA123'},'operador',o.id,o.version);o=await s.saveOrder({...o,status:'delivered'},'operador',o.id,o.version);assert.equal(o.history.length,4);assert.equal(o.history.at(-1).nextStatus,'delivered');}],
 ['no despacha por transportadora sin guía',async s=>{const p=await s.save('products',productData());const o=await s.saveOrder(orderData(p,{status:'preparing'}),'operador');await assert.rejects(()=>s.saveOrder({...o,status:'sent'},'operador',o.id,o.version));}],
 ['permite entrega local sin exigir transportadora',async s=>{const p=await s.save('products',productData());const o=await s.saveOrder(orderData(p,{status:'preparing',deliveryMethod:'local'}),'operador');const sent=await s.saveOrder({...o,status:'sent'},'operador',o.id,o.version);assert.equal(sent.status,'sent');}],
 ['cancelación requiere motivo y conserva registro',async s=>{const p=await s.save('products',productData()),o=await s.saveOrder(orderData(p),'operador');await assert.rejects(()=>s.saveOrder({...o,status:'cancelled'},'operador',o.id,o.version));const cancelled=await s.saveOrder({...o,status:'cancelled',statusReason:'Solicitud del comprador'},'operador',o.id,o.version);assert.equal(cancelled.status,'cancelled');assert.equal((await s.orders()).length,1);}],
 ['el pago completo requiere monto y fecha; no cambia envío',async s=>{const p=await s.save('products',productData()),o=await s.saveOrder(orderData(p),'operador');await assert.rejects(()=>s.saveOrder({...o,paymentStatus:'paid'},'operador',o.id,o.version));const paid=await s.saveOrder({...o,paymentStatus:'paid',paymentAmount:o.total,paymentDate:'2026-09-19'},'operador',o.id,o.version);assert.equal(paid.status,'new');assert.equal(paid.paymentStatus,'paid');assert.equal(paid.history.length,2);}],
 ['abonos manuales requieren valores parciales válidos',async s=>{const p=await s.save('products',productData()),o=await s.saveOrder(orderData(p),'operador');const partial=await s.saveOrder({...o,paymentStatus:'partial',paymentAmount:20000,paymentDate:'2026-09-19'},'operador',o.id,o.version);assert.equal(partial.paymentAmount,20000);await assert.rejects(()=>s.saveOrder({...partial,paymentAmount:partial.total},'operador',o.id,partial.version));}],
 ['no cambia totales después del despacho',async s=>{const p=await s.save('products',productData());let o=await s.saveOrder(orderData(p,{status:'preparing',deliveryMethod:'local'}),'operador');o=await s.saveOrder({...o,status:'sent'},'operador',o.id,o.version);await assert.rejects(()=>s.saveOrder({...o,shippingCost:1000},'operador',o.id,o.version),{status:409});}],
 ['conserva nombres y composición histórica de combos',async s=>{const p=await s.save('products',productData()),c=await s.save('combos',{...emptyRecord('combos'),title:'Combo original',slug:'combo',status:'published',price:50000,items:[{productId:p.id,quantity:2}]});const o=await s.saveOrder(orderData(p,{items:[{lineId:randomUUID(),kind:'combos',itemId:c.id,quantity:1,unitPrice:50000}]}),'operador');await s.save('combos',{...c,title:'Combo nuevo',items:[{productId:p.id,quantity:1}]},c.id,c.version);const saved=await s.saveOrder({...o,notes:'Actualización'},'operador',o.id,o.version);assert.equal(saved.items[0].title,'Combo original');assert.equal(saved.items[0].components[0].quantity,2);}],
 ['no elimina referencias asociadas a pedidos',async s=>{const p=await s.save('products',productData());await s.saveOrder(orderData(p),'operador');await assert.rejects(()=>s.remove('products',p.id,p.version),{status:409});}],
 ['protege pedidos de edición concurrente',async s=>{const p=await s.save('products',productData()),o=await s.saveOrder(orderData(p),'operador');await s.saveOrder({...o,notes:'Cambio 1'},'operador',o.id,1);await assert.rejects(()=>s.saveOrder({...o,notes:'Cambio 2'},'operador',o.id,1),{status:409});}],
 ['busca y pagina pedidos en la base',async s=>{const p=await s.save('products',productData());for(let i=0;i<23;i++)await s.saveOrder(orderData(p,{customerName:`Prueba ${i}`,tracking:i===0?'GUIA-UNICA':''}),'operador');assert.equal((await s.pageOrders()).records.length,20);assert.equal((await s.pageOrders({page:2})).records.length,3);assert.equal((await s.pageOrders({q:'GUIA-UNICA'})).total,1);assert.equal((await s.pageOrders({q:'AN-000001'})).total,1);}],
 ['comodines y SQL ingresados se tratan como datos',async s=>{const p=await s.save('products',productData());await s.saveOrder(orderData(p,{customerName:'Nombre con % literal'}),'operador');assert.equal((await s.pageOrders({q:'%'})).total,1);assert.equal((await s.pageOrders({q:"' OR 1=1 --"})).total,0);assert.equal((await s.list('products')).length,1);}],
 ['exporta negocio sin secretos de autenticación',async s=>{await createAdmin(s,'admin@example.com','clave-de-prueba-segura');const bundle=await s.exportData();assert.equal(bundle.format,'allnutrition-export-v2');assert.equal('users' in bundle,false);assert.ok(!JSON.stringify(bundle).includes('scrypt:'));}],
 ['cuentas individuales, sesiones revocables y contraseñas con hash',async s=>{await createAdmin(s,'admin@example.com','clave-de-prueba-segura');const auth=await login(s,'admin@example.com','clave-de-prueba-segura');assert.equal((await getSession(s,auth.token)).user.email,'admin@example.com');assert.ok((await s.db.get(`SELECT password FROM ${s.t('users')} WHERE email=?`,['admin@example.com'])).password.startsWith('scrypt:'));await logout(s,auth.token);assert.equal(await getSession(s,auth.token),null);}],
 ['cambiar contraseña revoca sesiones anteriores',async s=>{await createAdmin(s,'admin@example.com','clave-de-prueba-segura');const a=await login(s,'admin@example.com','clave-de-prueba-segura');await createAdmin(s,'admin@example.com','otra-clave-larga-segura',{reset:true});assert.equal(await getSession(s,a.token),null);await assert.rejects(()=>login(s,'admin@example.com','clave-de-prueba-segura'),{status:401});}],
 ['limita intentos de acceso con estado persistente',async s=>{for(let i=0;i<8;i++)await assert.rejects(()=>login(s,'nadie@example.com','contraseña-invalida'),{status:401});await assert.rejects(()=>login(s,'nadie@example.com','contraseña-invalida'),{status:429});}],
 ['importa solo en destino vacío, conserva IDs y exige revisar publicación',async s=>{const bundle={format:'allnutrition-export-v2',settings:{...defaults,launchApproved:true},orders:[],...Object.fromEntries(Object.keys((await import('../lib/schema.mjs')).schemas).map(k=>[k,[]]))};bundle.products=[{...productData(),id:randomUUID(),version:1,createdAt:'2026-09-19T00:00:00.000Z',updatedAt:'2026-09-19T00:00:00.000Z'}];await importData(s,bundle);assert.equal((await s.list('products'))[0].id,bundle.products[0].id);assert.equal((await s.settings()).launchApproved,false);await assert.rejects(()=>importData(s,bundle));}],
 ['revierte una importación inválida completa',async s=>{const bundle={format:'allnutrition-export-v2',settings:defaults,orders:[],...Object.fromEntries(Object.keys((await import('../lib/schema.mjs')).schemas).map(k=>[k,[]]))};bundle.products=[{...productData(),id:randomUUID(),version:1,createdAt:'2026-09-19',updatedAt:'2026-09-19',catalogIds:['inexistente']}];await assert.rejects(()=>importData(s,bundle));assert.equal((await s.list('products')).length,0);}],
];
export async function runContracts(t,factory) { for(const [name,execute] of contracts)await t.test(name,async()=>{const store=await factory();try{await execute(store);}finally{await store.close();}}); }
