import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { databaseConfig,allowedOrigins } from '../lib/db/config.mjs';
import { imageUrl,publicUrl,validateRecord,validateSettings,validateOrder,validateTransition } from '../lib/validation.mjs';
import { assertOrigin,assertCSRF,passwordMatches } from '../lib/auth.mjs';
import { emptyRecord, defaults,whatsAppLink } from '../lib/schema.mjs';
import { placeholders } from '../lib/db/postgres.mjs';
import { productData,orderData } from './contract.mjs';
for(const value of ['javascript:alert(1)','data:image/png;base64,YQ==','file:///tmp/a.png','http://example.com/a.png','https://user:secret@example.com/a.png','https://localhost/a.png','https://127.0.0.1/a.png','https://10.0.0.2/a.png','https://172.20.0.1/a.png','https://192.168.1.1/a.png','https://169.254.169.254/a.png','https://[::1]/a.png','/api/media/old','//example.com/image.png'])test(`rechaza imagen no permitida: ${value.split(':')[0]} / caso ${value.length}`,()=>assert.throws(()=>imageUrl(value)));
test('acepta HTTPS directo y las imágenes ya entregadas',()=>{assert.equal(imageUrl('https://example.com/a.jpg?width=500'),'https://example.com/a.jpg?width=500');assert.equal(imageUrl('/brand/logo.jpg'),'/brand/logo.jpg');assert.equal(imageUrl('/brand/creatina-vital-force.jpg'),'/brand/creatina-vital-force.jpg');});
test('permite referencias locales solo en imágenes de producto',()=>{const image='/api/media/550e8400-e29b-41d4-a716-446655440000';assert.equal(validateRecord('products',productData({image})).image,image);assert.throws(()=>validateRecord('catalogs',{...emptyRecord('catalogs'),title:'Colección',slug:'coleccion',image}));});
test('auto sin credenciales usa SQLite',()=>assert.equal(databaseConfig({}).provider,'sqlite'));
test('auto con credenciales usa Supabase',()=>assert.equal(databaseConfig({DATABASE_URL:'postgresql://user:password@example.com/db'}).provider,'supabase'));
test('rechaza supabase sin conexión y no finge fallback',()=>assert.throws(()=>databaseConfig({DB_DRIVER:'supabase'})));
test('rechaza conexión API en lugar de PostgreSQL',()=>assert.throws(()=>databaseConfig({DATABASE_URL:'https://example.supabase.co'})));
test('impide SQLite efímero en Vercel',()=>assert.throws(()=>databaseConfig({DB_DRIVER:'sqlite',VERCEL:'1'})));
test('no permite desactivar TLS remoto',()=>assert.throws(()=>databaseConfig({DATABASE_URL:'postgresql://u:p@remote.example.com/db',DB_SSL:'disable'})));
test('configuración usa URL de Supabase con prioridad explícita',()=>assert.equal(databaseConfig({SUPABASE_DATABASE_URL:'postgresql://u:p@chosen.example.com/db',DATABASE_URL:'postgresql://u:p@other.example.com/db'}).url,'postgresql://u:p@chosen.example.com/db'));
test('PostgreSQL exige una CA legible y no ambigua sin debilitar TLS', t => {
  const directory = mkdtempSync(join(tmpdir(), 'allnutrition-ca-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const file = join(directory, 'ca.crt');
  const env = { DB_DRIVER: 'supabase', DATABASE_URL: 'postgresql://u:p@db/allnutrition_test', DB_CA_CERT_FILE: file };
  assert.throws(() => databaseConfig(env), /No se puede leer DB_CA_CERT_FILE/);
  writeFileSync(file, ' \n');
  assert.throws(() => databaseConfig(env), /DB_CA_CERT_FILE está vacío/);
  assert.throws(() => databaseConfig({ ...env, DB_CA_CERT_FILE: directory }), /No se puede leer DB_CA_CERT_FILE/);
  const pem = '-----BEGIN CERTIFICATE-----\nfixture\n-----END CERTIFICATE-----\n';
  writeFileSync(file, pem);
  assert.equal(databaseConfig(env).ca, pem);
  assert.equal(databaseConfig(env).ssl, 'verify');
  assert.throws(() => databaseConfig({ ...env, DB_CA_CERT: pem }), /Configura solo DB_CA_CERT o DB_CA_CERT_FILE/);
  assert.throws(() => databaseConfig({ ...env, DB_SSL: 'disable' }), /No desactives TLS/);
  assert.equal(databaseConfig({ DB_DRIVER: 'sqlite', DB_CA_CERT_FILE: '/missing' }).provider, 'sqlite');
});
test('origin: no confía en dominios arbitrarios',()=>{assert.throws(()=>assertOrigin('https://evil.example.com',['https://shop.example.com']),{status:403});assertOrigin('https://shop.example.com',['https://shop.example.com']);assert.throws(()=>assertOrigin(null,['https://shop.example.com']));});
test('admite únicamente preview de Vercel proporcionado por entorno',()=>assert.deepEqual(allowedOrigins({NODE_ENV:'production',VERCEL:'1',VERCEL_URL:'test.vercel.app'}),['https://test.vercel.app']));
test('CSRF rechaza tokens ausentes, incorrectos y largos distintos',()=>{assertCSRF('same','same');assert.throws(()=>assertCSRF('evil','same'),{status:403});assert.throws(()=>assertCSRF(null,'same'));assert.throws(()=>assertCSRF('longer','same'));});
test('WhatsApp recibe el producto codificado correctamente',()=>{const url=new URL(whatsAppLink(defaults,'Proteína & creatina'));assert.equal(url.hostname,'wa.me');assert.ok(url.searchParams.get('text').includes('Proteína & creatina'));});
test('rechaza nombres de secciones arbitrarias',()=>assert.throws(()=>validateRecord('users',{}),{status:404}));
test('rechaza enlaces de redes que no son los perfiles oficiales',()=>assert.throws(()=>validateSettings({...defaults,instagram:'https://example.com/profile'})));
test('rechaza precios negativos o decimales y texto nulo',()=>{assert.throws(()=>validateRecord('products',productData({price:-1})));assert.throws(()=>validateRecord('products',productData({price:1.5})));assert.throws(()=>validateRecord('products',null));});
test('JSON de pedido mal formado falla como validación',async()=>assert.rejects(()=>validateOrder(null,async()=>null),{status:400}));
test('estados finales no se reabren accidentalmente',()=>{assert.throws(()=>validateTransition('cancelled','new'),{status:409});assert.throws(()=>validateTransition('returned','preparing'),{status:409});});
test('PostgreSQL convierte parámetros de sentencias estáticas',()=>assert.equal(placeholders('SELECT * FROM records WHERE kind=? AND slug=?'),'SELECT * FROM records WHERE kind=$1 AND slug=$2'));
test('comprobantes también rechazan protocolos peligrosos',()=>assert.throws(()=>publicUrl('javascript:alert(1)')));
test('hash mal formado no autoriza',async()=>assert.equal(await passwordMatches('password','invalid'),false));
test('no acepta fecha imposible en pago',async()=>{const p={...productData(),id:'product'};await assert.rejects(()=>validateOrder(orderData(p,{paymentDate:'2026-02-30'}),async()=>p));});
