'use client';
import { useState,useEffect,useCallback,useRef } from 'react';
import Link from 'next/link';
import { schemas,settingsFields,emptyRecord,money,orderStates,contentStates,paymentStates } from '@/lib/schema.mjs';
import { Field } from './Fields';
import RecordEditor from './RecordEditor';
import OrderEditor from './OrderEditor';
import Icon from './Icons';
import ImageByUrl from './ImageByUrl';
const sectionNames={home:'Resumen',...Object.fromEntries(Object.entries(schemas).map(([k,v])=>[k,v.label])),orders:'Pedidos',settings:'Contacto y redes'};
const nav=[['home','grid'],['products','box'],['catalogs','grid'],['combos','box'],['orders','truck'],['faqs','chat'],['messages','edit'],['shipping','truck'],['settings','sun']];
export default function Admin({csrf,user}){
 const [section,setSection]=useState('home'),[all,setAll]=useState(null),[settings,setSettings]=useState(null),[orderData,setOrderData]=useState({records:[],total:0,page:1,pageSize:20});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[page,setPage]=useState(1);
 const settingsSnapshot=useRef('');
 const api=useCallback(async (path,options={})=>{const r=await fetch(path,{...options,cache:'no-store',headers:{'Content-Type':'application/json','x-csrf-token':csrf,...options.headers}});const d=await r.json();if(r.status===401){window.location.assign('/admin/login');throw new Error('Sesión vencida.');}if(!r.ok)throw new Error(d.error||'No se pudo completar la operación.');return d;},[csrf]);
 const load=useCallback(async()=>{setError('');try{const keys=Object.keys(schemas);const values=await Promise.all(keys.map(k=>api(`/api/admin/${k}`)));setAll(Object.fromEntries(keys.map((k,i)=>[k,values[i].records])));const currentSettings=await api('/api/admin/settings');setSettings(currentSettings);settingsSnapshot.current=JSON.stringify(currentSettings);}catch(e){setError(e.message);}finally{setLoading(false);}},[api]);
 const requestSequence=useRef(0);
 const loadOrders=useCallback(async()=>{const sequence=++requestSequence.current;try{const q=new URLSearchParams({page:String(page),q:section==='orders'?query:'',status:section==='orders'?filter:''});const data=await api(`/api/admin/orders?${q}`);if(sequence===requestSequence.current)setOrderData(data);}catch(e){setError(e.message);}},[api,page,query,filter,section]);
 useEffect(()=>{load();},[load]);useEffect(()=>{const timer=setTimeout(loadOrders,200);return()=>clearTimeout(timer);},[loadOrders]);
 function navigate(key){if(section==='settings'&&JSON.stringify(settings)!==settingsSnapshot.current&&!window.confirm('Hay cambios de configuración sin guardar. ¿Descartarlos?'))return;setSection(key);setQuery('');setFilter('');setPage(1);setEditing(null);setNotice('');setError('');}
 async function saved(){setEditing(null);setNotice('Cambios guardados. La vitrina muestra el contenido publicado al volver a cargarla.');await Promise.all([load(),loadOrders()]);}
 async function editOrder(record){try{const d=await api(`/api/admin/orders/${record.id}`);setEditing({kind:'orders',record:d});}catch(e){setError(e.message);}}
 async function saveSettings(e){e.preventDefault();setBusy(true);setError('');try{const currentSettings=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(settings)});setSettings(currentSettings);settingsSnapshot.current=JSON.stringify(currentSettings);setNotice('Configuración guardada.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function signOut(){if(section==='settings'&&JSON.stringify(settings)!==settingsSnapshot.current&&!window.confirm('Hay cambios sin guardar. ¿Cerrar sesión de todas formas?'))return;try{await api('/api/auth/logout',{method:'POST'});window.location.assign('/admin/login');}catch(e){setError(e.message);}}
 useEffect(()=>{const handler=e=>{if(section==='settings'&&settings&&JSON.stringify(settings)!==settingsSnapshot.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[section,settings]);
 const statusLabel=v=>(contentStates.find(s=>s.value===v)||orderStates.find(s=>s.value===v))?.label||v;
 const rows=all&&schemas[section]?(all[section]||[]).filter(r=>(!filter||r.status===filter)&&r.title.toLowerCase().includes(query.toLowerCase())):[];
 return <div className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" href="/"><ImageByUrl src="/brand/logo.jpg" alt="" width="47" height="47"/><span>ALL NUTRITION<small>ADMINISTRACIÓN</small></span></Link><p className="sidebar-label">TU ESPACIO DE TRABAJO</p><nav aria-label="Administración">{nav.map(([key,icon])=><button key={key} className={section===key?'active':''} onClick={()=>navigate(key)}><Icon name={icon} size={19}/>{sectionNames[key]}{key==='products'&&all&&<span className="nav-count">{all.products.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="user-avatar">AN</div><div><strong>Administrador</strong><span>{user.email}</span></div><button aria-label="Cerrar sesión" title="Cerrar sesión" onClick={signOut}><Icon name="external" size={17}/></button></div></aside><div className="admin-main"><header className="admin-topbar"><div><span className="eyebrow">PANEL DE CONTROL</span><span className="topbar-breadcrumb">All Nutrition <Icon name="chevron" size={13}/> {sectionNames[section]}</span></div><div className="topbar-actions"><a className="button subtle compact" href="/?preview=1" target="_blank" rel="noopener noreferrer">Ver mi página <Icon name="external" size={15}/></a><button className="icon-button" aria-label="Cerrar sesión" title="Cerrar sesión" onClick={signOut}><Icon name="lock" size={17}/></button></div></header><main className="admin-content"><div className="admin-heading"><div><p className="eyebrow">{section==='home'?'TU NEGOCIO, EN ORDEN':'AUTOGESTIÓN'}</p><h1>{section==='home'?'Hola, All Nutrition.':sectionNames[section]}</h1><p>{section==='home'?'Actualiza tu vitrina y registra lo acordado con tus compradores.':schemas[section]?.help|| (section==='orders'?'Registro manual de pedidos recibidos por WhatsApp.':'Administra los canales y los datos públicos de tu marca.')}</p></div>{all&&schemas[section]&&<button className="button primary" onClick={()=>setEditing({kind:section,record:emptyRecord(section)})}><Icon name="plus"/>Crear {schemas[section].singular}</button>}{all&&section==='orders'&&<button className="button primary" onClick={()=>setEditing({kind:'orders',record:null})}><Icon name="plus"/>Nuevo pedido</button>}</div>
 {error&&<div className="error alert" role="alert">{error}<button className="text-button" onClick={()=>{load();loadOrders();}}>Reintentar</button></div>}{notice&&<div className="success alert" role="status"><Icon name="check" size={17}/>{notice}<button className="icon-button" aria-label="Cerrar aviso" onClick={()=>setNotice('')}><Icon name="close" size={15}/></button></div>}
 {loading&&<div className="empty-card">Cargando el panel…</div>}
 {!loading&&all&&section==='home'&&<><div className="stats-grid">{[['Productos publicados',all.products.filter(p=>p.status==='published').length,'box'],['Catálogos',all.catalogs.length,'grid'],['Combos publicados',all.combos.filter(p=>p.status==='published').length,'box'],['Pedidos registrados',orderData.total,'truck']].map(([label,value,icon])=><article className="stat-card" key={label}><span>{label}<Icon name={icon}/></span><strong>{value}</strong><small>Registro actual del panel</small></article>)}</div><div className="dashboard-columns"><section className="dashboard-card"><div className="card-heading"><h2>Tu siguiente actualización</h2><span className="pill">Fase 1</span></div><p className="muted">Empieza por lo que tus clientes necesitan ver.</p>{[['products','Actualizar catálogo','Nombres, fotos, presentaciones y precios.'],['settings','Completar redes sociales','Agrega los enlaces oficiales de Facebook e Instagram.'],['shipping','Confirmar datos de envío','Zonas, costos y condiciones aprobadas.']].map(([key,title,desc])=><button className="task-row" key={key} onClick={()=>navigate(key)}><span className="task-icon"><Icon name={key==='shipping'?'truck':key==='products'?'box':'external'}/></span><span><strong>{title}</strong><small>{desc}</small></span><Icon name="chevron" size={16}/></button>)}</section><section className="dashboard-card dark-card"><p className="eyebrow">ASÍ FUNCIONA TU VITRINA</p><h2>La consulta llega<br/>a WhatsApp.</h2><p>Después de conversar con el comprador, registra el pedido aquí y actualiza su estado.</p><div className="flow-tags"><span>Catálogo</span><Icon name="arrow" size={14}/><span>WhatsApp</span><Icon name="arrow" size={14}/><span>Registro manual</span></div><button className="button light" onClick={()=>navigate('orders')}>Administrar pedidos <Icon name="arrow"/></button></section></div>{settings?.showNextStage&&<section className="next-stage"><span className="icon-circle"><Icon name="sun"/></span><div><p className="eyebrow">CUANDO NECESITES DAR EL SIGUIENTE PASO</p><h3>De registrar pedidos a dar seguimiento a oportunidades.</h3><p>Una siguiente etapa puede añadir captación de interesados, seguimiento comercial y organización del equipo. Se define y contrata por separado; no está activa en esta versión.</p></div><span className="pill outline">Ampliación opcional</span></section>}<div className="admin-bottom-note"><span>Los pedidos y sus datos de contacto solo se muestran en el panel privado.</span><a href="/api/admin/export">Exportar mis datos</a></div></>}
 {!loading&&all&&schemas[section]&&<section className="data-card"><div className="table-tools"><label className="search-box"><Icon name="search" size={18}/><input aria-label="Buscar registros" placeholder={`Buscar en ${schemas[section].label.toLowerCase()}`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar por publicación" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos los estados</option>{contentStates.map(s=><option value={s.value} key={s.value}>{s.label}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Contenido</th><th>Estado</th><th>{['products','combos'].includes(section)?'Precio':'Orden'}</th><th>Acción</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="row-identity">{r.image?<ImageByUrl src={r.image} alt=""/>:<span className="table-icon"><Icon name="box"/></span>}<div><strong>{r.title}</strong><small>{r.presentation||`/${r.slug}`}</small></div></div></td><td><span className={`pill ${r.status}`}>{statusLabel(r.status)}</span></td><td>{['products','combos'].includes(section)?money(r.price):r.sort}</td><td><button className="button subtle compact" onClick={()=>setEditing({kind:section,record:r})}><Icon name="edit" size={15}/>Editar</button></td></tr>)}</tbody></table></div>{rows.length===0&&<div className="empty-card"><Icon name="box" size={30}/><h3>No hay registros para mostrar.</h3><p>Crea tu primer contenido o ajusta el filtro.</p></div>}<div className="table-footer">{rows.length} registros · Publicar, archivar y editar está incluido en este panel.</div></section>}
 {!loading&&all&&section==='orders'&&<section className="data-card"><div className="hint flush">Este panel no lee tus conversaciones de WhatsApp ni confirma pagos o entregas automáticamente.</div><div className="table-tools"><label className="search-box"><Icon name="search" size={18}/><input aria-label="Buscar pedidos" placeholder="Nombre, teléfono, guía o AN-000001" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><select aria-label="Filtrar por estado del pedido" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="">Todos los estados</option>{orderStates.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Pedido</th><th>Comprador</th><th>Estado / pago</th><th>Total</th><th>Acción</th></tr></thead><tbody>{orderData.records.map(o=><tr key={o.id}><td><strong>AN-{String(o.number).padStart(6,'0')}</strong><small>{new Date(o.createdAt).toLocaleDateString('es-CO')}</small></td><td><strong>{o.customerName}</strong><small>{o.city} · {o.phone}</small></td><td><span className={`pill ${o.status}`}>{statusLabel(o.status)}</span><small>{paymentStates.find(p=>p.value===o.paymentStatus)?.label||o.paymentStatus}</small></td><td>{money(o.total)}</td><td><button className="button subtle compact" onClick={()=>editOrder(o)}>Abrir <Icon name="chevron" size={14}/></button></td></tr>)}</tbody></table></div>{orderData.records.length===0&&<div className="empty-card"><Icon name="truck" size={32}/><h3>Todavía no hay pedidos en esta vista.</h3><p>Registra únicamente pedidos reales acordados con tus compradores.</p></div>}<div className="table-footer"><span>{orderData.total} pedidos · Página {page}</span><div><button className="button subtle compact" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="button subtle compact" disabled={page*20>=orderData.total} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></div></section>}
 {!loading&&all&&section==='settings'&&settings&&<form className="settings-form" onSubmit={saveSettings}><div className="hint">Las redes son enlaces públicos; no necesitas compartir sus contraseñas. El mensaje prellenado puede usar {'{producto}'}. No es una respuesta automática.</div><div className="settings-fields">{settingsFields.map(f=><Field key={f.name} field={f} value={settings[f.name]} onChange={v=>setSettings(s=>({...s,[f.name]:v}))} all={all} csrf={csrf}/>)}</div><p className="small muted">Aprobar el contenido no compra ni conecta un dominio. Los canales sin enlace no aparecen en la vitrina.</p><button className="button primary" disabled={busy}>{busy?'Guardando…':'Guardar configuración'}<Icon name="check" size={16}/></button></form>}
 </main></div>{editing&&editing.kind!=='orders'&&<RecordEditor key={`${editing.kind}:${editing.record.id||'new'}`} {...editing} all={all} csrf={csrf} onClose={()=>setEditing(null)} onSaved={saved}/>} {editing?.kind==='orders'&&<OrderEditor key={editing.record?.id||'new-order'} record={editing.record} all={all} csrf={csrf} onClose={()=>setEditing(null)} onSaved={saved}/>}</div>;
}
