'use client';
import { useEffect, useRef, useState } from 'react';
import Icon from './Icons';
import ImageByUrl from './ImageByUrl';
export function Field({field:f,value,onChange,all,csrf,onUploading}){
 const options=all?.[f.source]||[];
 if(f.type==='checkbox')return <label className="checkbox-field"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{f.label}</span></label>;
 if(f.type==='image')return <ImageLink label={f.label} value={value||''} onChange={onChange} csrf={csrf} onUploading={onUploading} allowUpload={f.localUpload===true}/>;
 if(f.type==='multi')return <fieldset className="field"><legend>{f.label}</legend>{options.length===0?<p className="small muted">Primero crea un catálogo.</p>:<div className="check-grid">{options.map(o=><label key={o.id}><input type="checkbox" checked={(value||[]).includes(o.id)} onChange={e=>onChange(e.target.checked?[...(value||[]),o.id]:(value||[]).filter(x=>x!==o.id))}/>{o.title}</label>)}</div>}</fieldset>;
 if(f.type==='comboItems')return <fieldset className="field"><legend>{f.label}</legend>{(value||[]).map((line,i)=><div className="combo-line" key={i}><select aria-label={`Producto ${i+1} del combo`} value={line.productId} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,productId:e.target.value}:x))} required><option value="">Selecciona un producto</option>{options.map(p=><option value={p.id} key={p.id}>{p.title} · {p.presentation}</option>)}</select><input aria-label={`Cantidad ${i+1}`} type="number" min="1" max="999" value={line.quantity} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/><button className="icon-button" aria-label="Quitar producto" type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}><Icon name="close" size={16}/></button></div>)}<button type="button" className="button subtle compact" onClick={()=>onChange([...(value||[]),{productId:'',quantity:1}])}><Icon name="plus" size={15}/>Agregar producto</button></fieldset>;
 return <label className="field">{f.label}{f.required&&<span className="required"> *</span>}{f.type==='textarea'?<textarea value={value??''} required={!!f.required} maxLength={f.max||5000} onChange={e=>onChange(e.target.value)} rows={4}/>:f.type==='select'?<select value={value??''} onChange={e=>onChange(e.target.value)}>{f.options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:<input value={value??''} type={f.type==='money'||f.type==='number'?'number':f.type==='url'?'url':f.type==='email'?'email':'text'} required={!!f.required} min={f.type==='money'||f.type==='number'?f.min||0:undefined} step={f.type==='money'||f.type==='number'?1:undefined} maxLength={f.max||2000} onChange={e=>onChange(f.type==='money'||f.type==='number'?Number(e.target.value):e.target.value)}/>}</label>;
}

function ImageLink({label,value,onChange,csrf,onUploading,allowUpload}) {
 const [tested,setTested]=useState(''),[failed,setFailed]=useState(false);
 const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[usage,setUsage]=useState(null),[usageError,setUsageError]=useState('');
 const stagedImages=useRef(new Set());
 const bundled=['/brand/logo.jpg','/brand/creatina-vital-force.jpg'].includes(value);
 const localImage=allowUpload&&/^\/api\/media\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value);
 let valid=bundled||localImage;
 try { const u=new URL(value);valid ||= u.protocol==='https:'&&!u.username&&!u.password&&/\.[a-z]{2,}$/i.test(u.hostname)&&!/(localhost|\.local|\.internal|\.lan)$/i.test(u.hostname); }catch{}
 useEffect(()=>{if(!allowUpload)return;let active=true;fetch('/api/admin/upload',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo consultar el almacenamiento.');if(active)setUsage(current=>current&&current.used>d.used?current:d);}).catch(e=>{if(active)setUsageError(e.message);});return()=>{active=false;};},[allowUpload]);
 useEffect(()=>{if(!allowUpload)return;return()=>{for(const url of stagedImages.current)fetch('/api/admin/upload',{method:'DELETE',headers:{'x-csrf-token':csrf,'Content-Type':'application/json'},body:JSON.stringify({url})}).catch(()=>{});stagedImages.current.clear();};},[allowUpload,csrf]);
 async function releaseStaged(keep=''){let usage=null;for(const url of [...stagedImages.current]){if(url===keep)continue;const r=await fetch('/api/admin/upload',{method:'DELETE',headers:{'x-csrf-token':csrf,'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo liberar la imagen temporal.');stagedImages.current.delete(url);usage=d.usage;}return usage;}
 async function upload(file){onUploading?.(true);setUploading(true);setUploadError('');try{const r=await fetch('/api/admin/upload',{method:'POST',headers:{'x-csrf-token':csrf,'Content-Type':file.type||'application/octet-stream'},body:file});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo subir la imagen.');stagedImages.current.add(d.url);onChange(d.url);setTested(d.url);setFailed(false);setUsage(d.usage);setUsageError('');const cleanedUsage=await releaseStaged(d.url);if(cleanedUsage)setUsage(cleanedUsage);}catch(e){setUploadError(e.message);}finally{setUploading(false);onUploading?.(false);}}
 const mb=value=>`${new Intl.NumberFormat('es-CO',{maximumFractionDigits:3}).format(value/1_000_000)} MB`;
 return <div className="field"><label>{label}<input aria-label={label} type="text" inputMode="url" maxLength={2048} value={value} placeholder="https://dominio-publico.com/producto.jpg" onChange={e=>{onChange(e.target.value);setTested('');setFailed(false);}}/></label>
 {allowUpload?<><p className="small muted">Pega una imagen HTTPS pública o sube JPEG, PNG o WebP de hasta 10 MiB. Se guarda en este servidor, se convierte a WebP y se reduce como máximo a 2400 px por lado. Si el selector del dispositivo ofrece iCloud Drive, puedes elegir desde allí un archivo compatible; también consume este almacenamiento local.</p><div className="image-upload"><label>Subir imagen del producto<input aria-label="Archivo de imagen del producto" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)upload(file);}}/></label>{usage?<p className="small muted" role="status">Almacenamiento local de imágenes: {mb(usage.used)} de {mb(usage.limit)} (1 GB).</p>:<p className="small muted" role="status">Consultando almacenamiento local…</p>}{usageError&&<p className="error" role="alert">{usageError}</p>}{uploading&&<p className="small muted" role="status">Optimizando y subiendo imagen…</p>}{uploadError&&<p className="error" role="alert">{uploadError}</p>}</div></>:<p className="small muted">Pega el enlace directo de una imagen pública. No se sube ni se copia ningún archivo. Los enlaces de publicaciones o carpetas no son imágenes directas.</p>}
 <div className="image-link-actions"><button type="button" className="button subtle compact" disabled={!valid} onClick={()=>{setTested(value);setFailed(false);}}>Verificar vista previa</button>{value&&<button type="button" className="text-button" onClick={()=>{onChange('');setTested('');}}>Quitar imagen</button>}</div>
 {tested&&<div className="image-picker"><ImageByUrl key={tested} src={tested} alt="Vista previa" onError={()=>setFailed(true)}/><p className="small">{failed?'El navegador no pudo mostrarla. Comprueba que el enlace sea público, directo y no haya caducado.':tested.startsWith('/api/media/')?'La imagen optimizada se sirve desde el almacenamiento local de este servidor.':'La imagen se carga desde su dirección original. Su disponibilidad depende de ese sitio.'}</p></div>}
 {value&&!valid&&<p className="error">Usa un enlace HTTPS público o una de las imágenes originales incorporadas.</p>}
 </div>;
}
