'use client';
import { useState, useRef } from 'react';
import { orderStates, orderTransitions, paymentStates, paymentMethods, money } from '@/lib/schema.mjs';
import Icon from './Icons';
import useDialog from './useDialog';
const blank = () => ({ requestId: crypto.randomUUID(), customerName:'',phone:'',city:'',department:'',address:'',addressNotes:'',email:'',documentType:'',documentNumber:'',notes:'',carrier:'',tracking:'',status:'new',statusReason:'',paymentStatus:'pending',paymentMethod:paymentMethods[0],paymentAmount:0,paymentDate:'',paymentReference:'',paymentReceiptUrl:'',deliveryMethod:'carrier',estimatedDelivery:'',shippingCost:0,items:[] });
export default function OrderEditor({ record, all, csrf, onClose, onSaved }) {
  const [initial] = useState(() => record ? { ...blank(), ...record, items:record.items.map(line => ({ ...line, lineId:line.lineId || crypto.randomUUID() })) } : blank());
  const [form,setForm] = useState(initial), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const dialog = useRef(null), close = useDialog(dialog,{busy,dirty:JSON.stringify(form)!==JSON.stringify(initial),onClose});
  const options = [...all.products.map(p=>({...p,kind:'products'})),...all.combos.map(p=>({...p,kind:'combos'}))];
  const frozen = record && ['sent','delivered','returned','cancelled'].includes(record.status);
  const total = form.items.reduce((sum,line)=>sum+(line.unitPrice||0)*(line.quantity||0),0)+(form.shippingCost||0);
  const allowedStates = record ? [record.status,...(orderTransitions[record.status]||[])] : ['new','preparing'];
  const set=(key,value)=>setForm(old=>({...old,[key]:value}));
  const lineChange=(index,change)=>setForm(old=>({...old,items:old.items.map((line,i)=>i===index?{...line,...change}:line)}));
  function selectLine(index,value){const [kind,itemId]=value.split(':');const item=options.find(o=>o.kind===kind&&o.id===itemId);lineChange(index,{kind:kind||'products',itemId:itemId||'',unitPrice:item?.price||0});}
  async function save(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try {
    const response=await fetch(`/api/admin/orders${record?.id?`/${record.id}`:''}`,{method:record?.id?'PUT':'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify(form)});
    const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo guardar.');await onSaved();
  }catch(error){setError(error.message);}finally{setBusy(false);}}
  const input=(name,label,required=false,type='text',disabled=false)=><label className="field" key={name}>{label}{required&&' *'}<input name={name} type={type} value={form[name]??''} required={required} disabled={disabled} min={type==='number'?0:undefined} step={type==='number'?1:undefined} maxLength={['address','addressNotes'].includes(name)?500:name==='paymentReceiptUrl'?2048:name==='email'?254:150} onChange={e=>set(name,type==='number'?Number(e.target.value):e.target.value)}/></label>;
  return <div className="drawer-backdrop"><section ref={dialog} className="editor-drawer wide" role="dialog" aria-modal="true" aria-labelledby="order-title">
    <header><div><p className="eyebrow">REGISTRO MANUAL</p><h2 id="order-title">{record?.id?`Pedido AN-${String(record.number).padStart(6,'0')}`:'Nuevo pedido'}</h2></div><button className="icon-button" aria-label="Cerrar pedido" onClick={close} disabled={busy}><Icon name="close"/></button></header>
    <form onSubmit={save}><fieldset className="editor-fieldset" disabled={busy}><div className="drawer-body">
      <p className="hint">Registra el pedido acordado por WhatsApp. Un clic o una consulta no crea un pedido. Los cambios no descuentan inventario ni verifican pagos.</p>
      <h3>1. Destinatario</h3><div className="form-grid">{input('customerName','Nombre completo',true)}{input('phone','Celular',true,'tel')}{input('city','Ciudad',true)}{input('department','Departamento')}{input('email','Correo electrónico',false,'email')}</div>
      {input('address','Dirección exacta')}{input('addressNotes','Barrio, apartamento y referencias')}
      <details className="optional-fields"><summary>Documento, solo cuando lo exige la transportadora</summary><div className="form-grid">{input('documentType','Tipo de documento')}{input('documentNumber','Número de documento')}</div></details>
      <h3>2. Productos y valor acordado</h3>{frozen&&<p className="hint">Las referencias y totales quedan conservados después del despacho o cierre.</p>}
      {form.items.map((line,index)=><div className="order-line" key={line.lineId}><label>Producto o combo<select disabled={frozen} value={line.itemId?`${line.kind}:${line.itemId}`:''} required onChange={event=>selectLine(index,event.target.value)}><option value="">Selecciona una referencia</option>{options.filter(p=>p.status==='published'||(p.id===line.itemId&&p.kind===line.kind)).map(p=><option disabled={p.availability==='soldout'&&p.id!==line.itemId} key={`${p.kind}:${p.id}`} value={`${p.kind}:${p.id}`}>{p.title}{p.presentation?` · ${p.presentation}`:''}{p.kind==='combos'?' (combo)':''}{p.availability==='soldout'?' · Agotado':''}</option>)}</select></label><div className="order-line-numbers"><label>Cantidad<input aria-label={`Cantidad línea ${index+1}`} disabled={frozen} type="number" min="1" max="999" required value={line.quantity} onChange={event=>lineChange(index,{quantity:Number(event.target.value)})}/></label><label>Precio unitario (COP)<input aria-label={`Precio línea ${index+1}`} disabled={frozen} type="number" min="1" step="1" required value={line.unitPrice} onChange={event=>lineChange(index,{unitPrice:Number(event.target.value)})}/></label><button disabled={frozen} className="icon-button" type="button" aria-label="Quitar línea" onClick={()=>set('items',form.items.filter((_,i)=>i!==index))}><Icon name="close" size={17}/></button></div></div>)}
      {!frozen&&<button type="button" className="button subtle compact" onClick={()=>set('items',[...form.items,{lineId:crypto.randomUUID(),kind:'products',itemId:'',quantity:1,unitPrice:0}])}><Icon name="plus" size={16}/>Agregar referencia</button>}
      <h3>3. Entrega y estado</h3><div className="form-grid"><label className="field">Modalidad<select value={form.deliveryMethod} onChange={e=>set('deliveryMethod',e.target.value)}><option value="carrier">Transportadora</option><option value="local">Entrega local</option><option value="pickup">Recogida presencial</option></select></label>
      {input('shippingCost','Costo de envío (COP)',true,'number',frozen)}{input('carrier','Transportadora')}{input('tracking','Número de guía')}{input('estimatedDelivery','Fecha estimada',false,'date')}
      <label className="field">Estado del pedido<select value={form.status} onChange={e=>set('status',e.target.value)}>{orderStates.map(state=><option key={state.value} value={state.value} disabled={!allowedStates.includes(state.value)}>{state.label}</option>)}</select></label></div>
      <p className="small muted">Nuevo → Preparando → Enviado → Entregado. Enviado significa despachado o listo para recoger. Cancelado y Devuelto requieren motivo.</p>
      {['cancelled','returned'].includes(form.status)&&<label className="field">Motivo *<textarea required maxLength={500} value={form.statusReason} onChange={e=>set('statusReason',e.target.value)}/></label>}
      <h3>4. Pago manual</h3><div className="form-grid"><label className="field">Método<select value={form.paymentMethod} onChange={e=>set('paymentMethod',e.target.value)}>{paymentMethods.map(method=><option key={method}>{method}</option>)}</select></label><label className="field">Estado de pago<select value={form.paymentStatus} onChange={e=>set('paymentStatus',e.target.value)}>{paymentStates.map(state=><option key={state.value} value={state.value}>{state.label}</option>)}</select></label>{input('paymentAmount','Valor recibido / registrado (COP)',true,'number')}{input('paymentDate','Fecha de pago',false,'date')}{input('paymentReference','Referencia / nota del pago o reembolso')}{input('paymentReceiptUrl','Enlace HTTPS del comprobante',false,'url')}</div>
      <button type="button" className="button subtle compact" disabled={!total} onClick={()=>setForm(old=>({...old,paymentStatus:'paid',paymentAmount:total,paymentDate:old.paymentDate||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}))}>Completar pago total revisado</button>
      <p className="small muted">Usa este botón solo después de revisar el pago. No valida bancos. El enlace solo se muestra en el panel; no se descarga al servidor. Los permisos del archivo los controla su sitio de origen: no publiques comprobantes con acceso abierto.</p>
      <label className="field">Notas internas<textarea maxLength={3000} rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></label>
      <div className="order-total"><span>Total registrado</span><strong>{money(total)}</strong></div>
      {record?.history?.length>0&&<div className="history"><h3>Historial de cambios</h3>{record.history.map((event,index)=><div key={index}><strong>{orderStates.find(s=>s.value===event.nextStatus)?.label} · {paymentStates.find(s=>s.value===event.nextPaymentStatus)?.label||'Estado anterior'}</strong><p className="small">{new Date(event.createdAt).toLocaleString('es-CO',{timeZone:'America/Bogota'})}{event.reason&&` · ${event.reason}`}</p>{event.changedFields?.length>0&&<p className="small muted">{event.changedFields.length} campos actualizados · Operador {event.actorEmail||event.actorId.slice(0,8)}</p>}</div>)}</div>}
      {error&&<p className="error" role="alert">{error}</p>}
    </div><footer><span className="small muted">{record?.id?'El historial se conserva.':'Guardado protegido contra reintentos duplicados.'}</span><button className="button subtle" type="button" onClick={close}>Cerrar</button><button className="button primary">{busy?'Guardando…':'Guardar pedido'}</button></footer></fieldset></form>
  </section></div>;
}
