'use client';
import { useState } from 'react';
import Link from 'next/link';
import Icon from './Icons';
import ImageByUrl from './ImageByUrl';
import { money,whatsAppLink } from '@/lib/schema.mjs';
export default function Storefront({data,selected=null,initialCatalog=null}){
 const {settings:s,products,catalogs,combos,faqs,messages,shipping}=data;
 const [category,setCategory]=useState(initialCatalog||''),[query,setQuery]=useState('');
 const hero=messages.find(m=>m.placement==='hero'),announcement=messages.find(m=>m.placement==='announcement');
 const social=[{label:'Instagram',href:s.instagram},{label:'Facebook',href:s.facebook}].filter(x=>x.href);
 const shown=products.filter(p=>(!category||p.catalogIds.includes(category))&&(`${p.title} ${p.presentation} ${p.flavor}`).toLowerCase().includes(query.toLowerCase()));
 const highlighted=products.find(p=>p.featured)||products[0];
 const visibleCatalogs=catalogs.filter(c=>products.some(p=>p.catalogIds.includes(c.id))||combos.some(p=>p.catalogIds.includes(c.id)));
 const visibleCombos=combos.filter(c=>(!category||c.catalogIds.includes(category))&&(`${c.title} ${c.description}`).toLowerCase().includes(query.toLowerCase()));
 const activeCatalog=catalogs.find(c=>c.id===category);
 const wa=(product)=>whatsAppLink(s,product);
 return <div className="storefront">
 {!s.launchApproved&&<div className="review-banner">VISTA DE REVISIÓN · Información y publicación pendientes de aprobación</div>}
 {announcement&&<div className="announcement">{announcement.title}{announcement.body&&` · ${announcement.body}`}</div>}
 <header className="site-header"><Link href="/" className="wordmark"><ImageByUrl src={s.logo||'/brand/logo.jpg'} width="62" height="62" alt=""/><span>{s.brandName}</span></Link><nav aria-label="Navegación principal"><Link href="/#catalogo">Catálogo</Link>{combos.length>0&&<Link href="/#combos">Combos</Link>}<Link href="/#como-comprar">Cómo comprar</Link></nav><a className="button dark compact" href={wa()} target="_blank" rel="noopener noreferrer"><Icon name="chat"/><span>Hablemos</span></a></header>
 <main>
 {selected?<section className="detail wrap"><Link className="text-link" href="/#catalogo">← Volver al catálogo</Link><div className="detail-grid"><div className="detail-photo">{selected.image?<ImageByUrl src={selected.image} alt={selected.title}/>:<Icon name="box" size={100}/>}</div><div><p className="eyebrow">{selected.kind==='combos'?'COMBO':'CATÁLOGO ALL NUTRITION'}</p><h1>{selected.title}</h1>{selected.presentation&&<p>{selected.presentation} · {selected.flavor}</p>}<p>{selected.description}</p><p className="detail-price">{money(selected.price)}</p><p className="small muted">Confirma disponibilidad, condiciones de pago y costo de envío con nuestro equipo.</p>{selected.kind==='combos'&&<div className="combo-list">{selected.items.map(i=><p key={i.productId}>{i.quantity} × {products.find(p=>p.id===i.productId)?.title}</p>)}</div>}<a href={wa(selected.title)} className="button primary" target="_blank" rel="noopener noreferrer"><Icon name="chat"/>{selected.availability==='soldout'?'Consultar reposición':'Consultar por WhatsApp'}</a>{selected.productInfo&&<div className="product-notes"><h3>Información del producto</h3><p>{selected.productInfo}</p></div>}{selected.conditions&&<p>{selected.conditions}</p>}</div></div></section>:<section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span/> {s.brandName}</p><h1>{hero?.title||s.tagline}</h1><p className="hero-description">{hero?.body||'Conoce el catálogo y conversa con nuestro equipo por WhatsApp.'}</p><div className="hero-actions"><a href="#catalogo" className="button primary">Explorar catálogo <Icon name="arrow"/></a><a className="text-link" href={wa()} target="_blank" rel="noopener noreferrer">{hero?.buttonText||'Hablar por WhatsApp'} <Icon name="chat"/></a></div><div className="hero-caption"><span className="caption-line"/>{s.tagline}</div></div><div className="hero-visual"><div className="hero-ring"/><div className="vertical-label">ALL NUTRITION · COLOMBIA</div>{highlighted?.image?<ImageByUrl className="hero-product" src={highlighted.image} alt={highlighted.title}/>:<ImageByUrl className="hero-product" src={s.logo} alt={s.brandName}/>}<div className="hero-product-note"><span className="eyebrow">EN EL CATÁLOGO</span><strong>{highlighted?.title||s.brandName}</strong><span>{highlighted?.presentation||s.tagline}</span></div><span className="graphic-plus">+</span></div></section>}
 <div className="service-band"><div className="wrap service-inner"><span><Icon name="box"/>Productos y presentaciones</span><span><Icon name="chat"/>Atención por WhatsApp</span><span><Icon name="truck"/>Consulta opciones de envío</span></div></div>
 <section className="section wrap" id="catalogo"><div className="section-heading"><div><p className="eyebrow">ELIGE TU PRÓXIMO PRODUCTO</p><h2>Explora el catálogo<span>.</span></h2></div><p>Información clara.<br/>Atención directa con nuestro equipo.</p></div><div className="catalog-tools"><div className="filter-tabs" role="group" aria-label="Filtrar por catálogo"><button className={!category?'active':''} onClick={()=>setCategory('')}>Todos</button>{visibleCatalogs.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.title}</button>)}</div><label className="search-box"><Icon name="search"/><input aria-label="Buscar productos" placeholder="Buscar un producto" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div>{activeCatalog&&<article className="active-catalog">{activeCatalog.image&&<ImageByUrl src={activeCatalog.image} alt={activeCatalog.title}/>}<div><h3>{activeCatalog.title}</h3><p>{activeCatalog.description}</p><Link href={`/catalogos/${activeCatalog.slug}`} className="text-link">Ver este catálogo</Link></div></article>}</div><div className="products-grid">{shown.map(p=><article className="product-card" key={p.id}><Link href={`/productos/${p.slug}`} className="product-photo"><span className={`product-badge ${p.availability==='soldout'?'unavailable':''}`}>{p.availability==='available'?'Disponible':p.availability==='soldout'?'Agotado':'Consulta disponibilidad'}</span>{p.image?<ImageByUrl src={p.image} alt={p.title} loading="lazy"/>:<Icon name="box" size={70}/>}<span className="photo-arrow"><Icon name="arrow"/></span></Link><div className="product-content"><span className="eyebrow">{catalogs.find(c=>p.catalogIds.includes(c.id))?.title||'ALL NUTRITION'}</span><h3><Link href={`/productos/${p.slug}`}>{p.title}</Link></h3><p>{p.presentation}{p.flavor&&` · ${p.flavor}`}</p><div className="price-row"><strong>{money(p.price)}</strong><small>COP</small></div><a className="button product-cta" href={wa(p.title)} target="_blank" rel="noopener noreferrer"><Icon name="chat"/>{p.availability==='soldout'?'Consultar reposición':'Consultar este producto'}</a></div></article>)}{shown.length===0&&<p className="empty-card">No hay referencias publicadas para esta búsqueda.</p>}<aside className="catalog-note"><span className="icon-circle"><Icon name="chat" size={26}/></span><p className="eyebrow">CONVERSEMOS</p><h3>¿Buscas otra<br/>referencia?</h3><p>Escríbenos para consultar productos y presentaciones.</p><a className="text-link" href={wa()} target="_blank" rel="noopener noreferrer">Hablar con el equipo <Icon name="arrow"/></a></aside></div></section>
 {visibleCombos.length>0&&<section className="section combos-section" id="combos"><div className="wrap"><p className="eyebrow">PRODUCTOS QUE VAN JUNTOS</p><h2>Combos del catálogo<span>.</span></h2><div className="combos-grid">{visibleCombos.map(c=><article className="combo-card" key={c.id}>{c.image&&<ImageByUrl src={c.image} alt={c.title} loading="lazy"/>}<div><h3>{c.title}</h3><p>{c.description}</p><strong>{money(c.price)}</strong><Link className="text-link" href={`/combos/${c.slug}`}>Ver el combo <Icon name="arrow"/></Link></div></article>)}</div></div></section>}
 <section className="section wrap how-to" id="como-comprar"><div><p className="eyebrow">DE LA VITRINA A TU WHATSAPP</p><h2>Comprar empieza<br/>con una conversación<span>.</span></h2><p>No necesitas crear una cuenta en la página.</p><a className="button dark" href={wa()} target="_blank" rel="noopener noreferrer"><Icon name="chat"/>Empezar mi consulta</a></div><div className="steps">{[['01','Encuentra tu producto','Revisa su presentación, precio e información en el catálogo.'],['02','Habla con nuestro equipo','El botón de WhatsApp abre una consulta sobre el producto elegido.'],['03','Confirma tu pedido','Acuerda disponibilidad, forma de pago y datos de envío con el equipo.']].map(([n,t,b])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></div>)}</div></section>
 {(shipping.length>0||s.paymentInfo)&&<section className="section info-section"><div className="wrap info-grid">{s.paymentInfo&&<article><Icon name="check"/><h3>Formas de pago</h3><p>{s.paymentInfo}</p><small>Las condiciones se confirman por WhatsApp.</small></article>}{shipping.map(z=><article key={z.id}><Icon name="truck"/><h3>{z.title}</h3>{[z.zone,z.costText,z.estimatedTime,z.cashOnDelivery,z.details].filter(Boolean).map((line,i)=><p key={i}>{line}</p>)}</article>)}</div></section>}
 {messages.filter(m=>m.placement==='feature').length>0&&<section className="section wrap feature-grid">{messages.filter(m=>m.placement==='feature').map(m=><article key={m.id}><h3>{m.title}</h3><p>{m.body}</p>{m.buttonText&&<a className="text-link" href={wa()} target="_blank" rel="noopener noreferrer">{m.buttonText} <Icon name="arrow"/></a>}</article>)}</section>}
 {faqs.length>0&&<section className="section wrap faq-section"><div><p className="eyebrow">ANTES DE ESCRIBIRNOS</p><h2>Resolvamos<br/>tus dudas<span>.</span></h2></div><div>{faqs.map(f=><details key={f.id}><summary>{f.title}<span>+</span></summary><p>{f.answer}</p></details>)}</div></section>}
 <section className="closing wrap"><div><p className="eyebrow">ESTAMOS AL OTRO LADO DEL CHAT</p><h2>Hablemos de tu próximo pedido.</h2></div><a className="button light" href={wa()} target="_blank" rel="noopener noreferrer">Ir a WhatsApp <Icon name="arrow"/></a></section>
 </main><footer className="site-footer wrap"><div className="footer-brand"><strong>{s.brandName}</strong><p>{s.tagline}</p></div><div><span className="eyebrow">CONTACTO</span><a href={wa()} target="_blank" rel="noopener noreferrer">WhatsApp · +{s.whatsapp}</a>{s.email&&<a href={`mailto:${s.email}`}>{s.email}</a>}{s.hours&&<span>{s.hours}</span>}</div>{social.length>0&&<div><span className="eyebrow">SÍGUENOS</span>{social.map(x=><a key={x.label} href={x.href} target="_blank" rel="noopener noreferrer">{x.label} <Icon name="external" size={13}/></a>)}</div>}<div className="footer-bottom"><span>{s.brandName}</span><span>Catálogo comercial · Atención por WhatsApp</span></div></footer><a className="floating-whatsapp" aria-label="Consultar por WhatsApp" href={wa()} target="_blank" rel="noopener noreferrer"><Icon name="chat" size={25}/></a>
 </div>;
}
